import type { GeneratedFile, ModuleStatusItem, ModuleStatusReport } from "@/lib/types"

type BuildProjectFilesInput = {
  prompt: string
  originalPrompt?: string | null
  projectName?: string | null
  providerMessage?: string | null
  promptSummary?: string | null
}

type BuildProjectFilesOutput = {
  message: string
  files: GeneratedFile[]
  moduleStatus: ModuleStatusReport
}

type BuildIntent = "dashboard" | "news" | "ecommerce" | "landing" | "portfolio" | "booking" | "crm" | "laundry" | "generic"

export function buildProjectFiles({
  prompt,
  originalPrompt,
  projectName,
  providerMessage,
  promptSummary,
}: BuildProjectFilesInput): BuildProjectFilesOutput {
  const name = sanitizeName(inferName(originalPrompt || prompt) || inferName(prompt) || projectName || "Swift Starter")
  const intent = inferBuildIntent(prompt)
  const brief = promptSummary || prompt
  const moduleStatus = buildModuleStatusReport({
    projectName: name,
    prompt: originalPrompt || prompt,
    intent,
    previewStatus: providerMessage ? "fallback" : "success",
  })

  const baseFiles = buildStandardStructureFiles(name)
  const domainOverrides =
    intent === "news"
      ? buildNewsPortalOverrideFiles(name, brief)
      : intent === "dashboard"
      ? buildDashboardOverrideFiles(name, brief)
      : intent === "ecommerce"
        ? buildCommerceOverrideFiles(name, brief)
        : intent === "landing"
          ? buildLandingOverrideFiles(name, brief)
          : intent === "portfolio"
            ? buildPortfolioOverrideFiles(name, brief)
            : intent === "booking"
              ? buildBookingOverrideFiles(name, brief)
              : intent === "crm"
                ? buildCrmOverrideFiles(name, brief)
                : intent === "laundry"
                  ? buildLaundryOverrideFiles(name, brief)
                  : buildGenericOverrideFiles(name, brief)

  const readme = buildReadmeFile({
    name,
    originalPrompt: originalPrompt || prompt,
    effectivePrompt: prompt,
    providerMessage,
  })

  const files = mergeFilesByPath([...baseFiles, readme], [
    ...domainOverrides,
    buildModuleStatusDataFile(moduleStatus),
  ])

  return {
    message: `Generated a full-stack ${intent} starter for ${name} using the standard Swift project tree.`,
    files,
    moduleStatus,
  }
}

function buildStandardStructureFiles(name: string): GeneratedFile[] {
  const safeName = serializeForCode(name)

  return [
    {
      path: "app/layout.tsx",
      language: "tsx",
      content: `import "./globals.css"

export const metadata = {
  title: ${safeName},
  description: "Generated by Swift Builder",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,
    },
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

export default function HomePage() {
  return (
    <main className="min-h-screen bg-neutral-950 px-6 py-20 text-white">
      <section className="mx-auto max-w-4xl rounded-3xl border border-white/10 bg-white/5 p-10">
        <h1 className="text-4xl font-semibold">Starter Project</h1>
        <p className="mt-4 text-neutral-300">Update this page from Code tab.</p>
      </section>
      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
    {
      path: "app/globals.css",
      language: "css",
      content: `:root {
  --background: #0a0a0a;
  --foreground: #fafafa;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: var(--background);
  color: var(--foreground);
  font-family: Inter, system-ui, sans-serif;
}
`,
    },
    {
      path: "app/api/health/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"

export async function GET() {
  return NextResponse.json({ ok: true, service: "swift-generated-app" })
}
`,
    },
    {
      path: "app/api/generate/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  const body = await request.json().catch(() => null)
  return NextResponse.json({ ok: true, received: body })
}
`,
    },
    {
      path: "app/api/projects/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"

export async function GET() {
  return NextResponse.json({ projects: [] })
}
`,
    },
    {
      path: "app/api/models/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"

export async function GET() {
  return NextResponse.json({
    models: [
      { key: "swift-2", label: "Swift AI", provider: "swift", price: 3000 },
    ],
  })
}
`,
    },
    {
      path: "components/build-status-panel.tsx",
      language: "tsx",
      content: `import type { ModuleStatusItem, ModuleStatusReport } from "@/lib/build-status"

function StatusList({ title, items }: { title: string; items: ModuleStatusItem[] }) {
  if (items.length === 0) {
    return null
  }

  return (
    <section className="rounded-xl border border-white/10 bg-white/[0.03] p-4">
      <h3 className="text-sm font-semibold text-white">{title}</h3>
      <ul className="mt-3 space-y-2">
        {items.map((item) => (
          <li key={item.name} className="rounded-lg bg-black/20 px-3 py-2">
            <p className="text-sm font-medium text-white">{item.name}</p>
            <p className="mt-1 text-xs text-neutral-400">{item.detail}</p>
          </li>
        ))}
      </ul>
    </section>
  )
}

export function BuildStatusPanel({ status }: { status: ModuleStatusReport }) {
  const tone =
    status.previewStatus === "success"
      ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-100"
      : status.previewStatus === "error"
        ? "border-rose-400/30 bg-rose-400/10 text-rose-100"
        : "border-amber-400/30 bg-amber-400/10 text-amber-100"

  return (
    <aside className="mx-auto mt-6 max-w-5xl rounded-2xl border border-white/10 bg-neutral-900/90 p-5 text-white shadow-2xl">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-xs uppercase tracking-[0.22em] text-neutral-400">Build Status</p>
          <h2 className="mt-2 text-2xl font-semibold">{status.projectName || "Generated Project"}</h2>
          <p className="mt-1 text-sm text-neutral-400">Current phase: {status.currentPhase}</p>
        </div>
        <span className={"w-fit rounded-full border px-3 py-1 text-xs font-medium " + tone}>
          Preview {status.previewStatus}
        </span>
      </div>

      <div className="mt-5 grid gap-4 lg:grid-cols-3">
        <StatusList title="Ready" items={status.ready} />
        <StatusList title="Partial" items={status.partial} />
        <StatusList title="Planned" items={status.planned} />
      </div>

      {status.errors.length > 0 && (
        <div className="mt-4">
          <StatusList title="Errors" items={status.errors} />
        </div>
      )}

      <section className="mt-4 rounded-xl border border-white/10 bg-white/[0.03] p-4">
        <h3 className="text-sm font-semibold text-white">Next Recommended Steps</h3>
        <ol className="mt-3 list-decimal space-y-2 pl-5 text-sm text-neutral-300">
          {status.nextSteps.map((step) => (
            <li key={step}>{step}</li>
          ))}
        </ol>
      </section>
    </aside>
  )
}
`,
    },
    {
      path: "components/ui/button.tsx",
      language: "tsx",
      content: `type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement>

export function Button({ className = "", ...props }: ButtonProps) {
  return (
    <button
      className={"inline-flex items-center justify-center rounded-md bg-white px-4 py-2 text-sm font-medium text-black " + className}
      {...props}
    />
  )
}
`,
    },
    {
      path: "components/ui/card.tsx",
      language: "tsx",
      content: `export function Card({ children }: { children: React.ReactNode }) {
  return <div className="rounded-lg border border-white/10 bg-white/5 p-6">{children}</div>
}
`,
    },
    {
      path: "components/dashboard/sidebar.tsx",
      language: "tsx",
      content: `export function DashboardSidebar() {
  return (
    <aside className="w-64 border-r border-white/10 p-4 text-sm text-neutral-300">
      <p className="font-semibold text-white">Sidebar</p>
      <ul className="mt-4 space-y-2">
        <li>Dashboard</li>
        <li>Projects</li>
        <li>Settings</li>
      </ul>
    </aside>
  )
}
`,
    },
    {
      path: "components/editor/chat-panel.tsx",
      language: "tsx",
      content: `export function ChatPanel() {
  return <div className="rounded-lg border border-white/10 p-4">Chat Panel</div>
}
`,
    },
    {
      path: "components/editor/preview-panel.tsx",
      language: "tsx",
      content: `export function PreviewPanel() {
  return <div className="rounded-lg border border-white/10 p-4">Preview Panel</div>
}
`,
    },
    {
      path: "hooks/use-mobile.ts",
      language: "ts",
      content: `import { useEffect, useState } from "react"

export function useMobile(breakpoint = 768) {
  const [isMobile, setIsMobile] = useState(false)

  useEffect(() => {
    const update = () => setIsMobile(window.innerWidth < breakpoint)
    update()
    window.addEventListener("resize", update)
    return () => window.removeEventListener("resize", update)
  }, [breakpoint])

  return isMobile
}
`,
    },
    {
      path: "hooks/use-toast.ts",
      language: "ts",
      content: `type Toast = { title: string; description?: string }

export function useToast() {
  return {
    toast(toast: Toast) {
      console.log("toast", toast)
    },
  }
}
`,
    },
    {
      path: "lib/env.ts",
      language: "ts",
      content: `export const env = {
  nodeEnv: process.env.NODE_ENV || "development",
  databaseUrl: process.env.DATABASE_URL || "",
  directDatabaseUrl: process.env.DIRECT_DATABASE_URL || "",
  openRouterApiKey: process.env.OPENROUTER_API_KEY || "",
}
`,
    },
    {
      path: "lib/utils.ts",
      language: "ts",
      content: `export function cn(...parts: Array<string | false | null | undefined>) {
  return parts.filter(Boolean).join(" ")
}
`,
    },
    {
      path: "lib/store.ts",
      language: "ts",
      content: `type AppState = {
  activeProjectId: string | null
}

export const appStore: AppState = {
  activeProjectId: null,
}
`,
    },
    {
      path: "lib/ai/config.ts",
      language: "ts",
      content: `export const AI_CONFIG = {
  provider: "swift",
  model: "swift-2",
  baseUrl: "/api/generate",
  timeoutMs: Number(process.env.AI_TIMEOUT_MS || 60000),
}
`,
    },
    {
      path: "lib/ai/client.ts",
      language: "ts",
      content: `import { AI_CONFIG } from "./config"

export async function generateText(prompt: string) {
  return {
    provider: AI_CONFIG.provider,
    model: AI_CONFIG.model,
    message: "Generated response for: " + prompt,
  }
}
`,
    },
    {
      path: "lib/services/project.service.ts",
      language: "ts",
      content: `type Project = { id: string; name: string; updatedAt: string }

export function listProjects(): Project[] {
  return []
}
`,
    },
    {
      path: "prisma/schema.prisma",
      language: "prisma",
      content: `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Project {
  id        String   @id @default(cuid())
  name      String
  prompt    String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
`,
    },
    {
      path: "public/site.webmanifest",
      language: "json",
      content: `{
  "name": "Swift Generated App",
  "short_name": "SwiftApp",
  "start_url": "/",
  "display": "standalone",
  "background_color": "#0a0a0a",
  "theme_color": "#0a0a0a"
}
`,
    },
    
    {
      path: ".env.example",
      language: "env",
      content: `DATABASE_URL="postgresql://user:password@ep-example-pooler.region.aws.neon.tech/neondb?sslmode=require"
DIRECT_DATABASE_URL="postgresql://user:password@ep-example.region.aws.neon.tech/neondb?sslmode=require"
NEXTAUTH_SECRET="replace-me"
OPENROUTER_API_KEY="replace-me"
OPENROUTER_BASE_URL="https://openrouter.ai/api/v1"
`,
    },
    {
      path: "auth.ts",
      language: "ts",
      content: `export const authConfig = {
  providers: ["credentials", "google"],
}
`,
    },
    {
      path: "components.json",
      language: "json",
      content: `{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "app/globals.css",
    "baseColor": "neutral",
    "cssVariables": true
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
`,
    },
    {
      path: "middleware.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"

export function middleware() {
  return NextResponse.next()
}
`,
    },
    {
      path: "next.config.mjs",
      language: "ts",
      content: `/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    unoptimized: true,
  },
}

export default nextConfig
`,
    },
    {
      path: "package.json",
      language: "json",
      content: `{
  "name": "swift-generated-app",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "16.2.0",
    "react": "19.2.4",
    "react-dom": "19.2.4"
  },
  "devDependencies": {
    "typescript": "5.7.3"
  }
}
`,
    },
    {
      path: "postcss.config.mjs",
      language: "ts",
      content: `export default {
  plugins: {},
}
`,
    },
    {
      path: "tsconfig.json",
      language: "json",
      content: `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": {
      "@/*": ["./src/*", "./*"],
      "~/*": ["./src/*", "./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
`,
    },
    {
      path: "styles/globals.css",
      language: "css",
      content: `/* global styles (no Tailwind) */
html, body { height: 100%; }
body { margin: 0; font-family: Inter, system-ui, sans-serif; }
`,
    }
  ]
}

function buildGenericOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-neutral-950 px-6 py-20 text-white">
      <section className="mx-auto max-w-4xl rounded-3xl border border-white/10 bg-white/5 p-10">
        <h1 className="text-4xl font-semibold">{projectName}</h1>
        <p className="mt-4 text-neutral-300">Build brief: {buildBrief}</p>
        <p className="mt-3 text-sm text-neutral-400">
          This output follows Swift standard structure: app, components, hooks, lib, prisma, public, styles.
        </p>
      </section>
      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
  ]
}

function buildLaundryOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

const packages = [
  { name: "Cuci Lipat", price: "Rp 7.000/kg", eta: "24 jam" },
  { name: "Cuci Setrika", price: "Rp 10.000/kg", eta: "36 jam" },
  { name: "Dry Clean", price: "Mulai Rp 35.000", eta: "48 jam" },
]

const orders = [
  { id: "LS-1042", customer: "Nadia Putri", service: "Cuci Setrika", status: "Pickup", total: "Rp 54.000" },
  { id: "LS-1041", customer: "Rafi Hidayat", service: "Dry Clean", status: "Diproses", total: "Rp 85.000" },
  { id: "LS-1040", customer: "Maya Sari", service: "Cuci Lipat", status: "Siap Antar", total: "Rp 42.000" },
]

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-slate-950 text-white">
      <section className="border-b border-white/10 bg-cyan-950/40">
        <div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 lg:grid-cols-[1.05fr_.95fr]">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.24em] text-cyan-300">Laundry service app</p>
            <h1 className="mt-4 text-4xl font-semibold tracking-tight md:text-5xl">{projectName}</h1>
            <p className="mt-4 max-w-2xl text-slate-300">Order form, dashboard admin, dan tabel order untuk operasional laundry harian.</p>
            <p className="mt-3 max-w-2xl text-sm text-slate-400">Build brief: {buildBrief}</p>
            <div className="mt-6 flex flex-wrap gap-3">
              <a href="#order-form" className="rounded-md bg-cyan-300 px-5 py-3 text-sm font-semibold text-slate-950">Buat order</a>
              <a href="#admin-orders" className="rounded-md border border-white/15 px-5 py-3 text-sm font-semibold text-white">Lihat dashboard</a>
            </div>
          </div>

          <div id="order-form" className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 shadow-2xl">
            <h2 className="text-xl font-semibold">Form order laundry</h2>
            <div className="mt-5 grid gap-3">
              <input className="rounded-lg border border-white/10 bg-slate-900 px-4 py-3 text-sm" placeholder="Nama pelanggan" />
              <input className="rounded-lg border border-white/10 bg-slate-900 px-4 py-3 text-sm" placeholder="Alamat pickup" />
              <select className="rounded-lg border border-white/10 bg-slate-900 px-4 py-3 text-sm">
                {packages.map((item) => (
                  <option key={item.name}>{item.name}</option>
                ))}
              </select>
              <div className="grid gap-3 sm:grid-cols-2">
                <input className="rounded-lg border border-white/10 bg-slate-900 px-4 py-3 text-sm" placeholder="Estimasi kg" />
                <input className="rounded-lg border border-white/10 bg-slate-900 px-4 py-3 text-sm" placeholder="Jam pickup" />
              </div>
              <button className="rounded-lg bg-cyan-300 px-4 py-3 text-sm font-semibold text-slate-950">Simpan order</button>
            </div>
          </div>
        </div>
      </section>

      <section className="mx-auto grid max-w-7xl gap-5 px-4 py-8 md:grid-cols-3">
        {packages.map((item) => (
          <article key={item.name} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
            <h3 className="text-lg font-semibold">{item.name}</h3>
            <p className="mt-3 text-2xl font-bold text-cyan-300">{item.price}</p>
            <p className="mt-2 text-sm text-slate-400">Estimasi selesai {item.eta}</p>
          </article>
        ))}
      </section>

      <section id="admin-orders" className="mx-auto max-w-7xl px-4 pb-10">
        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Admin dashboard</p>
              <h2 className="mt-2 text-2xl font-semibold">Tabel order aktif</h2>
            </div>
            <div className="grid grid-cols-3 gap-3 text-center text-sm">
              <div className="rounded-lg bg-slate-900 px-4 py-3"><b>18</b><span className="block text-slate-400">Order</span></div>
              <div className="rounded-lg bg-slate-900 px-4 py-3"><b>7</b><span className="block text-slate-400">Pickup</span></div>
              <div className="rounded-lg bg-slate-900 px-4 py-3"><b>5</b><span className="block text-slate-400">Antar</span></div>
            </div>
          </div>

          <div className="mt-5 overflow-x-auto">
            <table className="w-full min-w-[720px] text-left text-sm">
              <thead className="border-b border-white/10 text-slate-400">
                <tr>
                  <th className="py-3">ID</th>
                  <th>Pelanggan</th>
                  <th>Layanan</th>
                  <th>Status</th>
                  <th>Total</th>
                </tr>
              </thead>
              <tbody>
                {orders.map((order) => (
                  <tr key={order.id} className="border-b border-white/5">
                    <td className="py-3 font-mono text-cyan-200">{order.id}</td>
                    <td>{order.customer}</td>
                    <td>{order.service}</td>
                    <td><span className="rounded-full bg-cyan-300/10 px-3 py-1 text-xs text-cyan-200">{order.status}</span></td>
                    <td>{order.total}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
        <BuildStatusPanel status={moduleStatus} />
      </section>
    </main>
  )
}
`,
    },
    {
      path: "app/api/orders/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"
import { createLaundryOrder, listLaundryOrders } from "@/lib/services/laundry.service"

export async function GET() {
  const orders = await listLaundryOrders()
  return NextResponse.json({ orders, total: orders.length })
}

export async function POST(request: NextRequest) {
  const payload = await request.json().catch(() => null)
  const order = createLaundryOrder(payload)
  return NextResponse.json({ order }, { status: 201 })
}
`,
    },
    {
      path: "lib/services/laundry.service.ts",
      language: "ts",
      content: `const demoOrders = [
  { id: "LS-1042", customer: "Nadia Putri", service: "Cuci Setrika", status: "Pickup", total: 54000 },
  { id: "LS-1041", customer: "Rafi Hidayat", service: "Dry Clean", status: "Diproses", total: 85000 },
  { id: "LS-1040", customer: "Maya Sari", service: "Cuci Lipat", status: "Siap Antar", total: 42000 },
]

export async function listLaundryOrders() {
  return demoOrders
}

export function createLaundryOrder(payload: unknown) {
  const input = typeof payload === "object" && payload !== null ? payload as Record<string, unknown> : {}
  return {
    id: "LS-" + Math.floor(1000 + Math.random() * 9000),
    customer: String(input.customer || input.customerName || "Pelanggan baru"),
    address: String(input.address || "Alamat pickup belum diisi"),
    service: String(input.service || "Cuci Lipat"),
    weightKg: Number(input.weightKg || 0),
    status: "Menunggu pickup",
    total: Number(input.total || 0),
  }
}
`,
    },
  ]
}

function buildDashboardOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

const stats = [
  { label: "Revenue", value: "Rp 128.450.000", trend: "+12.4%" },
  { label: "Orders", value: "2,481", trend: "+8.1%" },
  { label: "Active Users", value: "9,204", trend: "+5.9%" },
  { label: "Conversion", value: "3.42%", trend: "+0.3%" },
]

const activities = [
  { title: "Invoice #INV-0324 paid", time: "2 minutes ago" },
  { title: "New user signed up", time: "9 minutes ago" },
  { title: "Project deployment completed", time: "23 minutes ago" },
  { title: "Payment method updated", time: "1 hour ago" },
]

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-neutral-950 text-white">
      <div className="mx-auto grid max-w-7xl gap-6 px-4 py-6 md:grid-cols-[260px_1fr]">
        <aside className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
          <p className="text-xs uppercase tracking-[0.2em] text-emerald-300">Workspace</p>
          <h1 className="mt-3 text-2xl font-semibold">{projectName}</h1>
          <p className="mt-2 text-sm text-neutral-400">Dashboard fallback mode</p>
          <nav className="mt-6 space-y-2 text-sm text-neutral-300">
            <a className="block rounded-lg bg-white/10 px-3 py-2">Overview</a>
            <a className="block rounded-lg px-3 py-2 hover:bg-white/5">Analytics</a>
            <a className="block rounded-lg px-3 py-2 hover:bg-white/5">Projects</a>
            <a className="block rounded-lg px-3 py-2 hover:bg-white/5">Settings</a>
          </nav>
        </aside>

        <section className="space-y-6">
          <header className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
            <h2 className="text-2xl font-semibold">Dashboard Overview</h2>
            <p className="mt-2 text-sm text-neutral-300">Build brief: {buildBrief}</p>
          </header>

          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            {stats.map((item) => (
              <article key={item.label} className="rounded-xl border border-white/10 bg-white/[0.03] p-4">
                <p className="text-xs uppercase tracking-wide text-neutral-400">{item.label}</p>
                <p className="mt-2 text-2xl font-semibold">{item.value}</p>
                <p className="mt-1 text-xs text-emerald-300">{item.trend}</p>
              </article>
            ))}
          </div>

          <article className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
            <h3 className="text-lg font-semibold">Recent Activity</h3>
            <ul className="mt-4 space-y-3 text-sm text-neutral-300">
              {activities.map((activity) => (
                <li key={activity.title} className="flex items-center justify-between rounded-lg bg-white/[0.02] px-3 py-2">
                  <span>{activity.title}</span>
                  <span className="text-xs text-neutral-500">{activity.time}</span>
                </li>
              ))}
            </ul>
          </article>
        </section>
        <BuildStatusPanel status={moduleStatus} />
      </div>
    </main>
  )
}
`,
    },
    {
      path: "app/api/dashboard/summary/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"
import { getDashboardSummary } from "@/lib/services/dashboard.service"

export async function GET() {
  const summary = await getDashboardSummary()
  return NextResponse.json(summary)
}
`,
    },
    {
      path: "lib/services/dashboard.service.ts",
      language: "ts",
      content: `export async function getDashboardSummary() {
  return {
    revenue: 128450000,
    orders: 2481,
    activeUsers: 9204,
    conversionRate: 3.42,
  }
}
`,
    },
  ]
}

function buildNewsPortalOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name || "Desa Buntu")
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import Link from "next/link"
import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"
import { listAgenda, listAnnouncements, listPosts } from "@/lib/services/news.service"

export default async function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}
  const posts = await listPosts()
  const announcements = await listAnnouncements()
  const agenda = await listAgenda()
  const featured = posts[0]

  return (
    <main className="min-h-screen bg-stone-50 text-stone-950">
      <section className="border-b border-emerald-900/10 bg-emerald-950 text-white">
        <div className="mx-auto grid max-w-7xl gap-8 px-5 py-12 lg:grid-cols-[1.2fr_0.8fr] lg:py-16">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.24em] text-emerald-200">Portal Berita Resmi</p>
            <h1 className="mt-4 text-4xl font-bold leading-tight md:text-6xl">{projectName}</h1>
            <p className="mt-5 max-w-2xl text-lg text-emerald-50/85">
              Informasi warga, kegiatan BUMDes, pengumuman layanan, dan agenda Pemerintah Desa Buntu dalam satu portal yang mudah dibaca.
            </p>
            <p className="mt-4 max-w-2xl text-sm text-emerald-100/70">Brief: {buildBrief}</p>
          </div>
          {featured && (
            <article className="rounded-xl border border-white/15 bg-white/10 p-5">
              <p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-200">Berita Utama</p>
              <h2 className="mt-3 text-2xl font-semibold">{featured.title}</h2>
              <p className="mt-3 text-sm text-emerald-50/80">{featured.excerpt}</p>
              <Link href={\`/posts/\${featured.slug}\`} className="mt-5 inline-flex rounded-md bg-white px-4 py-2 text-sm font-semibold text-emerald-950">
                Baca selengkapnya
              </Link>
            </article>
          )}
        </div>
      </section>

      <section className="mx-auto grid max-w-7xl gap-8 px-5 py-10 lg:grid-cols-[1fr_340px]">
        <div>
          <div className="mb-4 flex items-center justify-between">
            <h2 className="text-2xl font-bold">Berita Terkini Desa Buntu</h2>
            <Link href="/admin/posts" className="text-sm font-semibold text-emerald-700">Admin berita</Link>
          </div>
          <div className="grid gap-4 md:grid-cols-2">
            {posts.map((post) => (
              <article key={post.id} className="rounded-xl border border-stone-200 bg-white p-5 shadow-sm">
                <p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">{post.category.name}</p>
                <h3 className="mt-3 text-xl font-semibold">{post.title}</h3>
                <p className="mt-2 text-sm leading-6 text-stone-600">{post.excerpt}</p>
                <div className="mt-4 flex items-center justify-between text-xs text-stone-500">
                  <span>{post.publishedAt}</span>
                  <Link href={\`/posts/\${post.slug}\`} className="font-semibold text-emerald-700">Baca</Link>
                </div>
              </article>
            ))}
          </div>
        </div>

        <aside className="space-y-4">
          <section className="rounded-xl border border-amber-200 bg-amber-50 p-5">
            <h2 className="text-lg font-bold">Pengumuman Warga</h2>
            <div className="mt-4 space-y-3">
              {announcements.map((item) => (
                <article key={item.id} className="rounded-lg bg-white p-3">
                  <h3 className="font-semibold">{item.title}</h3>
                  <p className="mt-1 text-sm text-stone-600">{item.body}</p>
                </article>
              ))}
            </div>
          </section>

          <section className="rounded-xl border border-stone-200 bg-white p-5">
            <h2 className="text-lg font-bold">Agenda Kegiatan Desa</h2>
            <div className="mt-4 space-y-3">
              {agenda.map((item) => (
                <article key={item.id} className="border-l-4 border-emerald-600 pl-3">
                  <p className="text-xs font-semibold text-emerald-700">{item.date}</p>
                  <h3 className="font-semibold">{item.title}</h3>
                  <p className="text-sm text-stone-600">{item.location}</p>
                </article>
              ))}
            </div>
          </section>
        </aside>
      </section>

      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
    {
      path: "app/posts/[slug]/page.tsx",
      language: "tsx",
      content: `import Link from "next/link"
import { notFound } from "next/navigation"
import { getPostBySlug, listCommentsForPost } from "@/lib/services/news.service"
import { CommentForm } from "@/components/news/comment-form"

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const post = await getPostBySlug(slug)
  if (!post) notFound()
  const comments = await listCommentsForPost(post.id)

  return (
    <main className="min-h-screen bg-stone-50 text-stone-950">
      <article className="mx-auto max-w-3xl px-5 py-10">
        <Link href="/" className="text-sm font-semibold text-emerald-700">Kembali ke beranda</Link>
        <p className="mt-8 text-xs font-semibold uppercase tracking-[0.2em] text-emerald-700">{post.category.name}</p>
        <h1 className="mt-3 text-4xl font-bold leading-tight">{post.title}</h1>
        <div className="mt-3 text-sm text-stone-500">{post.publishedAt} oleh {post.authorName}</div>
        <div className="prose prose-stone mt-8 max-w-none">
          {post.body.split("\\n").map((paragraph) => (
            <p key={paragraph}>{paragraph}</p>
          ))}
        </div>
      </article>

      <section className="mx-auto max-w-3xl px-5 pb-12">
        <div className="rounded-xl border border-stone-200 bg-white p-5">
          <h2 className="text-xl font-bold">Komentar Warga</h2>
          <p className="mt-1 text-sm text-stone-600">Login Gmail dapat dihubungkan lewat NextAuth Google provider sebelum komentar dipublikasikan.</p>
          <CommentForm postId={post.id} />
          <div className="mt-6 space-y-3">
            {comments.map((comment) => (
              <article key={comment.id} className="rounded-lg bg-stone-50 p-3">
                <div className="text-sm font-semibold">{comment.authorName}</div>
                <p className="mt-1 text-sm text-stone-700">{comment.body}</p>
              </article>
            ))}
          </div>
        </div>
      </section>
    </main>
  )
}
`,
    },
    {
      path: "components/news/comment-form.tsx",
      language: "tsx",
      content: `"use client"

import { useState } from "react"

export function CommentForm({ postId }: { postId: string }) {
  const [body, setBody] = useState("")
  const [status, setStatus] = useState<"idle" | "saving" | "saved">("idle")

  async function submitComment(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setStatus("saving")
    await fetch("/api/comments", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ postId, body, authorName: "Warga Desa Buntu" }),
    })
    setBody("")
    setStatus("saved")
  }

  return (
    <form onSubmit={submitComment} className="mt-5 space-y-3">
      <textarea
        value={body}
        onChange={(event) => setBody(event.target.value)}
        required
        minLength={3}
        className="min-h-24 w-full rounded-lg border border-stone-300 px-3 py-2 text-sm"
        placeholder="Tulis komentar atau masukan untuk berita ini..."
      />
      <div className="flex items-center justify-between gap-3">
        <button className="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white" disabled={status === "saving"}>
          {status === "saving" ? "Mengirim..." : "Kirim komentar"}
        </button>
        <span className="text-xs text-stone-500">Masuk Gmail dapat diaktifkan via NextAuth Google.</span>
      </div>
    </form>
  )
}
`,
    },
    {
      path: "app/admin/posts/page.tsx",
      language: "tsx",
      content: `import Link from "next/link"
import { listCategories, listPosts } from "@/lib/services/news.service"

export default async function AdminPostsPage() {
  const posts = await listPosts()
  const categories = await listCategories()

  return (
    <main className="min-h-screen bg-stone-100 px-5 py-8 text-stone-950">
      <div className="mx-auto max-w-6xl">
        <div className="flex flex-col gap-3 border-b border-stone-300 pb-5 md:flex-row md:items-center md:justify-between">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-700">Admin Desa Buntu</p>
            <h1 className="mt-2 text-3xl font-bold">CRUD Berita</h1>
          </div>
          <Link href="/admin/categories" className="rounded-md border border-emerald-700 px-4 py-2 text-sm font-semibold text-emerald-800">Kelola kategori</Link>
        </div>

        <section className="mt-6 rounded-xl border border-stone-200 bg-white p-5">
          <h2 className="text-lg font-bold">Buat / Edit Artikel</h2>
          <form className="mt-4 grid gap-3 md:grid-cols-2">
            <input className="rounded-lg border px-3 py-2" placeholder="Judul berita" />
            <select className="rounded-lg border px-3 py-2">
              {categories.map((category) => (
                <option key={category.id}>{category.name}</option>
              ))}
            </select>
            <textarea className="min-h-28 rounded-lg border px-3 py-2 md:col-span-2" placeholder="Isi berita lengkap" />
            <button className="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white" type="button">Simpan draft berita</button>
          </form>
        </section>

        <section className="mt-6 overflow-hidden rounded-xl border border-stone-200 bg-white">
          <div className="grid grid-cols-[1fr_180px_160px] bg-stone-50 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-stone-500">
            <span>Judul</span>
            <span>Kategori</span>
            <span>Aksi</span>
          </div>
          {posts.map((post) => (
            <div key={post.id} className="grid grid-cols-[1fr_180px_160px] items-center border-t px-4 py-3 text-sm">
              <span className="font-medium">{post.title}</span>
              <span>{post.category.name}</span>
              <span className="flex gap-2">
                <button className="rounded border px-3 py-1">Edit</button>
                <button className="rounded border border-red-300 px-3 py-1 text-red-700">Hapus</button>
              </span>
            </div>
          ))}
        </section>
      </div>
    </main>
  )
}
`,
    },
    {
      path: "app/admin/categories/page.tsx",
      language: "tsx",
      content: `import { listCategories } from "@/lib/services/news.service"

export default async function AdminCategoriesPage() {
  const categories = await listCategories()

  return (
    <main className="min-h-screen bg-stone-100 px-5 py-8 text-stone-950">
      <div className="mx-auto max-w-4xl">
        <h1 className="text-3xl font-bold">Kategori Berita Desa</h1>
        <form className="mt-6 flex gap-2 rounded-xl border bg-white p-4">
          <input className="flex-1 rounded-lg border px-3 py-2" placeholder="Contoh: Info Warga" />
          <button className="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white" type="button">Tambah</button>
        </form>
        <div className="mt-6 grid gap-3">
          {categories.map((category) => (
            <article key={category.id} className="flex items-center justify-between rounded-xl border bg-white p-4">
              <div>
                <h2 className="font-semibold">{category.name}</h2>
                <p className="text-sm text-stone-600">{category.description}</p>
              </div>
              <div className="flex gap-2">
                <button className="rounded border px-3 py-1 text-sm">Edit</button>
                <button className="rounded border border-red-300 px-3 py-1 text-sm text-red-700">Hapus</button>
              </div>
            </article>
          ))}
        </div>
      </div>
    </main>
  )
}
`,
    },
    {
      path: "app/api/posts/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"
import { z } from "zod"
import { createPost, listPosts } from "@/lib/services/news.service"

const PostSchema = z.object({
  title: z.string().min(3),
  slug: z.string().min(3),
  body: z.string().min(10),
  categoryId: z.string().min(1),
})

export async function GET() {
  return NextResponse.json({ posts: await listPosts() })
}

export async function POST(request: NextRequest) {
  const parsed = PostSchema.safeParse(await request.json().catch(() => null))
  if (!parsed.success) return NextResponse.json({ error: "Invalid post payload" }, { status: 400 })
  return NextResponse.json({ post: await createPost(parsed.data) }, { status: 201 })
}
`,
    },
    {
      path: "app/api/posts/[id]/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"
import { deletePost, updatePost } from "@/lib/services/news.service"

export async function PATCH(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const body = await request.json().catch(() => ({}))
  return NextResponse.json({ post: await updatePost(id, body) })
}

export async function DELETE(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  await deletePost(id)
  return NextResponse.json({ ok: true })
}
`,
    },
    {
      path: "app/api/categories/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"
import { z } from "zod"
import { createCategory, listCategories } from "@/lib/services/news.service"

const CategorySchema = z.object({
  name: z.string().min(3),
  description: z.string().optional(),
})

export async function GET() {
  return NextResponse.json({ categories: await listCategories() })
}

export async function POST(request: NextRequest) {
  const parsed = CategorySchema.safeParse(await request.json().catch(() => null))
  if (!parsed.success) return NextResponse.json({ error: "Invalid category payload" }, { status: 400 })
  return NextResponse.json({ category: await createCategory(parsed.data) }, { status: 201 })
}
`,
    },
    {
      path: "app/api/comments/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"
import { z } from "zod"
import { createComment } from "@/lib/services/news.service"

const CommentSchema = z.object({
  postId: z.string().min(1),
  body: z.string().min(3),
  authorName: z.string().min(2).default("Warga Desa Buntu"),
})

export async function POST(request: NextRequest) {
  const parsed = CommentSchema.safeParse(await request.json().catch(() => null))
  if (!parsed.success) return NextResponse.json({ error: "Invalid comment payload" }, { status: 400 })
  return NextResponse.json({ comment: await createComment(parsed.data) }, { status: 201 })
}
`,
    },
    {
      path: "lib/services/news.service.ts",
      language: "ts",
      content: `const categories = [
  { id: "cat-info-warga", name: "Info Warga", description: "Layanan administrasi, imbauan, dan informasi harian warga." },
  { id: "cat-bumdes", name: "Kegiatan BUMDes", description: "Kabar usaha desa dan pemberdayaan ekonomi warga." },
  { id: "cat-pengumuman", name: "Pengumuman", description: "Pengumuman resmi Pemerintah Desa Buntu." },
]

const posts = [
  {
    id: "post-1",
    slug: "musyawarah-desa-buntu-2026",
    title: "Musyawarah Desa Buntu Bahas Prioritas Pembangunan 2026",
    excerpt: "Pemerintah Desa Buntu mengundang warga untuk menyampaikan aspirasi pembangunan dusun dan layanan publik.",
    body: "Pemerintah Desa Buntu menggelar musyawarah desa untuk membahas prioritas pembangunan 2026. Warga dapat menyampaikan usulan terkait infrastruktur, pelayanan administrasi, kegiatan pemuda, dan penguatan ekonomi desa.\\n\\nHasil musyawarah akan dirangkum sebagai bahan penyusunan rencana kerja pemerintah desa.",
    categoryId: "cat-pengumuman",
    authorName: "Admin Desa Buntu",
    publishedAt: "17 Mei 2026",
  },
  {
    id: "post-2",
    slug: "bumdes-buntu-buka-pelatihan-produk-lokal",
    title: "BUMDes Buntu Buka Pelatihan Pengemasan Produk Lokal",
    excerpt: "Pelaku UMKM desa mengikuti pelatihan kemasan dan pemasaran digital untuk memperluas jangkauan produk lokal.",
    body: "BUMDes Buntu membuka pelatihan pengemasan produk lokal bagi pelaku UMKM. Kegiatan ini membantu warga meningkatkan nilai jual produk dan mempersiapkan katalog digital desa.",
    categoryId: "cat-bumdes",
    authorName: "Pengurus BUMDes",
    publishedAt: "16 Mei 2026",
  },
  {
    id: "post-3",
    slug: "jadwal-pelayanan-administrasi-desa",
    title: "Jadwal Pelayanan Administrasi Desa Pekan Ini",
    excerpt: "Pelayanan surat keterangan, domisili, dan pengantar warga dibuka Senin sampai Jumat pukul 08.00-14.00.",
    body: "Kantor Desa Buntu membuka pelayanan administrasi warga pada hari kerja. Warga diminta membawa identitas dan dokumen pendukung agar proses pelayanan berjalan lancar.",
    categoryId: "cat-info-warga",
    authorName: "Pelayanan Desa",
    publishedAt: "15 Mei 2026",
  },
]

const comments = [
  { id: "comment-1", postId: "post-1", authorName: "Siti Aminah", body: "Semoga usulan perbaikan jalan dusun bisa masuk prioritas." },
  { id: "comment-2", postId: "post-1", authorName: "Rahmat", body: "Mohon jadwal musyawarah juga diumumkan lewat grup warga." },
]

export async function listCategories() {
  return categories
}

export async function createCategory(input: { name: string; description?: string }) {
  return { id: \`cat-\${Date.now()}\`, name: input.name, description: input.description || "" }
}

export async function listPosts() {
  return posts.map((post) => ({
    ...post,
    category: categories.find((category) => category.id === post.categoryId) || categories[0],
  }))
}

export async function getPostBySlug(slug: string) {
  return (await listPosts()).find((post) => post.slug === slug) || null
}

export async function createPost(input: { title: string; slug: string; body: string; categoryId: string }) {
  return {
    id: \`post-\${Date.now()}\`,
    excerpt: input.body.slice(0, 140),
    authorName: "Admin Desa Buntu",
    publishedAt: new Date().toLocaleDateString("id-ID", { dateStyle: "medium" }),
    ...input,
  }
}

export async function updatePost(id: string, input: Record<string, unknown>) {
  return { id, ...input }
}

export async function deletePost(id: string) {
  return { id, deleted: true }
}

export async function listCommentsForPost(postId: string) {
  return comments.filter((comment) => comment.postId === postId)
}

export async function createComment(input: { postId: string; body: string; authorName: string }) {
  return { id: \`comment-\${Date.now()}\`, ...input }
}

export async function listAnnouncements() {
  return [
    { id: "ann-1", title: "Pendataan Kartu Keluarga", body: "Warga diminta memperbarui data KK di kantor desa pekan ini." },
    { id: "ann-2", title: "Kerja Bakti Jumat", body: "Kerja bakti dimulai pukul 07.00 di halaman balai desa." },
  ]
}

export async function listAgenda() {
  return [
    { id: "agenda-1", date: "20 Mei 2026", title: "Posyandu Balita", location: "Balai Desa Buntu" },
    { id: "agenda-2", date: "24 Mei 2026", title: "Pelatihan UMKM BUMDes", location: "Aula BUMDes" },
    { id: "agenda-3", date: "28 Mei 2026", title: "Musyawarah Dusun", location: "Kantor Desa" },
  ]
}
`,
    },
    {
      path: "prisma/schema.prisma",
      language: "prisma",
      content: `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Category {
  id          String   @id @default(cuid())
  name        String
  slug        String   @unique
  description String?
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  posts Post[]

  @@map("categories")
}

model Post {
  id          String   @id @default(cuid())
  categoryId  String
  title       String
  slug        String   @unique
  excerpt     String?
  body        String
  status      String   @default("draft")
  authorName  String   @default("Admin Desa Buntu")
  publishedAt DateTime?
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  category Category @relation(fields: [categoryId], references: [id], onDelete: Restrict)
  comments Comment[]

  @@index([categoryId])
  @@index([status, publishedAt])
  @@map("posts")
}

model Comment {
  id          String   @id @default(cuid())
  postId      String
  authorName  String
  authorEmail String?
  body        String
  status      String   @default("pending")
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  post Post @relation(fields: [postId], references: [id], onDelete: Cascade)

  @@index([postId, createdAt])
  @@index([status])
  @@map("comments")
}
`,
    },
    {
      path: ".env.example",
      language: "env",
      content: `DATABASE_URL="postgresql://USER:PASSWORD@HOST:5432/desa_buntu"
NEXTAUTH_SECRET="replace-with-secret"
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
`,
    },
  ]
}

function buildCommerceOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-neutral-950 px-6 py-16 text-white">
      <section className="mx-auto max-w-5xl rounded-3xl border border-white/10 bg-gradient-to-br from-orange-500/25 via-orange-600/10 to-neutral-900 p-10">
        <span className="rounded-full border border-orange-300/30 px-3 py-1 text-xs tracking-[0.2em] text-orange-200">
          {projectName}
        </span>
        <h1 className="mt-5 text-4xl font-semibold leading-tight">Build a modern commerce storefront</h1>
        <p className="mt-3 max-w-2xl text-neutral-300">Build brief: {buildBrief}</p>
      </section>
      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
    {
      path: "app/api/products/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"
import { listProducts } from "@/lib/services/catalog.service"

export async function GET() {
  const products = await listProducts()
  return NextResponse.json({ products, total: products.length })
}
`,
    },
    {
      path: "app/api/orders/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  const payload = await request.json()
  const customerName = payload?.customerName
  const items = payload?.items

  if (!customerName || !Array.isArray(items) || items.length === 0) {
    return NextResponse.json({ error: "customerName and items are required" }, { status: 400 })
  }

  return NextResponse.json({
    success: true,
    order: {
      id: "ord-" + Date.now(),
      customerName,
      itemCount: items.length,
      status: "pending-payment",
    },
  })
}
`,
    },
    {
      path: "lib/services/catalog.service.ts",
      language: "ts",
      content: `type Product = {
  id: string
  name: string
  price: number
  stock: number
}

const mockProducts: Product[] = [
  { id: "prod-1", name: "Starter Item", price: 149000, stock: 20 },
  { id: "prod-2", name: "Popular Item", price: 299000, stock: 50 },
  { id: "prod-3", name: "Premium Item", price: 499000, stock: 15 },
]

export async function listProducts(): Promise<Product[]> {
  return mockProducts
}
`,
    },
    {
      path: "prisma/schema.prisma",
      language: "prisma",
      content: `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Product {
  id          String   @id @default(cuid())
  name        String
  slug        String   @unique
  description String
  price       Int
  stock       Int
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}

model Order {
  id           String   @id @default(cuid())
  customerName String
  status       String   @default("pending-payment")
  totalAmount  Int
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
}
`,
    },
  ]
}

function buildLandingOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

const features = [
  "Conversion-focused hero with strong value proposition",
  "Social proof and trust indicators",
  "Clear call-to-action for demo or signup",
]

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-white text-slate-900">
      <header className="border-b border-slate-200 bg-white/90 backdrop-blur">
        <nav className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4">
          <p className="text-lg font-semibold">{projectName}</p>
          <a href="#cta" className="rounded-full bg-slate-900 px-4 py-2 text-sm font-medium text-white">Start Free</a>
        </nav>
      </header>
      <section className="mx-auto max-w-6xl px-4 py-16 md:py-24">
        <h1 className="max-w-3xl text-4xl font-bold tracking-tight md:text-6xl">Build trust fast and convert visitors into customers.</h1>
        <p className="mt-5 max-w-2xl text-base text-slate-600 md:text-lg">Build brief: {buildBrief}</p>
        <div className="mt-8 flex flex-wrap gap-3">
          <a id="cta" href="#" className="rounded-full bg-slate-900 px-5 py-3 text-sm font-medium text-white">Book a Demo</a>
          <a href="#" className="rounded-full border border-slate-300 px-5 py-3 text-sm font-medium text-slate-900">See Pricing</a>
        </div>
      </section>
      <section className="mx-auto grid max-w-6xl gap-4 px-4 pb-16 md:grid-cols-3">
        {features.map((item) => (
          <article key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-5">
            <h2 className="text-base font-semibold">{item}</h2>
          </article>
        ))}
      </section>
      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
    {
      path: "app/api/leads/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  const payload = await request.json()
  const email = payload?.email

  if (!email) {
    return NextResponse.json({ error: "email is required" }, { status: 400 })
  }

  return NextResponse.json({ ok: true, message: "Lead captured", email })
}
`,
    },
    {
      path: "lib/services/lead.service.ts",
      language: "ts",
      content: `type LeadInput = { email: string; source?: string }

export async function captureLead(input: LeadInput) {
  return {
    id: "lead-" + Date.now(),
    email: input.email,
    source: input.source || "landing-page",
  }
}
`,
    },
  ]
}

function buildPortfolioOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

const projects = [
  { title: "Identity System Revamp", result: "+37% conversion" },
  { title: "SaaS Onboarding UX", result: "-42% drop-off" },
  { title: "B2B Dashboard Redesign", result: "+28 NPS" },
]

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-stone-50 text-stone-900">
      <header className="mx-auto flex max-w-6xl items-center justify-between px-4 py-6">
        <p className="font-semibold">{projectName}</p>
        <a href="#contact" className="rounded-full bg-stone-900 px-4 py-2 text-sm text-white">Hire Me</a>
      </header>
      <section className="mx-auto max-w-6xl px-4 py-12 md:py-16">
        <p className="text-sm uppercase tracking-[0.2em] text-stone-500">Personal Brand Site</p>
        <h1 className="mt-4 max-w-3xl text-4xl font-bold md:text-6xl">Designing digital products that grow real business metrics.</h1>
        <p className="mt-5 max-w-2xl text-stone-600">Build brief: {buildBrief}</p>
      </section>
      <section className="mx-auto grid max-w-6xl gap-4 px-4 pb-16 md:grid-cols-3">
        {projects.map((project) => (
          <article key={project.title} className="rounded-2xl border border-stone-200 bg-white p-5">
            <h2 className="font-semibold">{project.title}</h2>
            <p className="mt-2 text-sm text-stone-600">{project.result}</p>
          </article>
        ))}
      </section>
      <footer id="contact" className="border-t border-stone-200 px-4 py-8 text-center text-sm text-stone-600">
        Ready to collaborate? Contact via portfolio inquiry form.
      </footer>
      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
    {
      path: "app/api/inquiry/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  const payload = await request.json()
  if (!payload?.name || !payload?.email) {
    return NextResponse.json({ error: "name and email are required" }, { status: 400 })
  }

  return NextResponse.json({ ok: true, status: "received" })
}
`,
    },
  ]
}

function buildBookingOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

const slots = [
  { id: "slot-1", label: "Mon 09:00", available: true },
  { id: "slot-2", label: "Mon 11:00", available: false },
  { id: "slot-3", label: "Tue 14:00", available: true },
]

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}
  const availableSlots = slots.filter((slot) => slot.available)

  return (
    <main className="min-h-screen bg-slate-950 px-4 py-10 text-slate-100 md:px-6">
      <header className="mx-auto flex w-full max-w-5xl items-center justify-between">
        <h1 className="text-2xl font-semibold">{projectName}</h1>
        <a href="#book" className="rounded-full bg-cyan-400 px-4 py-2 text-sm font-medium text-slate-950">Reserve Now</a>
      </header>
      <section className="mx-auto mt-8 w-full max-w-5xl rounded-2xl border border-white/10 bg-white/5 p-6">
        <h2 className="text-2xl font-semibold">Reservation System</h2>
        <p className="mt-2 text-sm text-slate-300">Build brief: {buildBrief}</p>
      </section>
      <section id="book" className="mx-auto mt-6 w-full max-w-5xl rounded-2xl border border-white/10 bg-white/5 p-6">
        <h3 className="text-lg font-medium">Available Slots</h3>
        {availableSlots.length === 0 ? (
          <p className="mt-4 text-sm text-slate-400">No slots available yet. Please check again later.</p>
        ) : (
          <ul className="mt-4 grid gap-3 sm:grid-cols-2">
            {availableSlots.map((slot) => (
              <li key={slot.id} className="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">{slot.label}</li>
            ))}
          </ul>
        )}
      </section>
      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
    {
      path: "app/api/bookings/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"
import { createBooking } from "@/lib/services/booking.service"

export async function POST(request: NextRequest) {
  const payload = await request.json()

  if (!payload?.customerName || !payload?.slotId) {
    return NextResponse.json({ error: "customerName and slotId are required" }, { status: 400 })
  }

  const booking = await createBooking(payload.customerName, payload.slotId)
  return NextResponse.json({ ok: true, booking })
}
`,
    },
    {
      path: "lib/services/booking.service.ts",
      language: "ts",
      content: `export async function createBooking(customerName: string, slotId: string) {
  return {
    id: "book-" + Date.now(),
    customerName,
    slotId,
    status: "confirmed",
  }
}
`,
    },
  ]
}

function buildCrmOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { BuildStatusPanel } from "@/components/build-status-panel"
import { moduleStatus } from "@/lib/build-status"

const leads = [
  { id: "lead-1", name: "Ari Putra", stage: "Qualified", value: "Rp 45.000.000" },
  { id: "lead-2", name: "Bina Group", stage: "Proposal", value: "Rp 120.000.000" },
  { id: "lead-3", name: "Citra Labs", stage: "Negotiation", value: "Rp 80.000.000" },
]

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-zinc-950 px-4 py-10 text-zinc-100 md:px-6">
      <header className="mx-auto flex w-full max-w-6xl items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold">{projectName}</h1>
          <p className="mt-1 text-sm text-zinc-400">Internal CRM dashboard</p>
        </div>
        <a href="#" className="rounded-full bg-emerald-400 px-4 py-2 text-sm font-medium text-zinc-950">Add New Lead</a>
      </header>
      <section className="mx-auto mt-8 w-full max-w-6xl rounded-2xl border border-white/10 bg-white/5 p-6">
        <p className="text-sm text-zinc-300">Build brief: {buildBrief}</p>
      </section>
      <section className="mx-auto mt-6 w-full max-w-6xl rounded-2xl border border-white/10 bg-white/5 p-6">
        <h2 className="text-lg font-medium">Lead Pipeline</h2>
        {leads.length === 0 ? (
          <p className="mt-4 text-sm text-zinc-400">No leads yet. Start by adding your first opportunity.</p>
        ) : (
          <ul className="mt-4 space-y-3">
            {leads.map((lead) => (
              <li key={lead.id} className="flex flex-col gap-1 rounded-xl border border-white/10 bg-white/5 p-3 sm:flex-row sm:items-center sm:justify-between">
                <p className="font-medium">{lead.name}</p>
                <p className="text-sm text-zinc-300">{lead.stage}</p>
                <p className="text-sm text-emerald-300">{lead.value}</p>
              </li>
            ))}
          </ul>
        )}
      </section>
      <BuildStatusPanel status={moduleStatus} />
    </main>
  )
}
`,
    },
    {
      path: "app/api/leads/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"
import { listLeads, createLead } from "@/lib/services/crm.service"

export async function GET() {
  const leads = await listLeads()
  return NextResponse.json({ leads })
}

export async function POST(request: NextRequest) {
  const payload = await request.json()
  if (!payload?.name) {
    return NextResponse.json({ error: "name is required" }, { status: 400 })
  }

  const lead = await createLead(payload.name, payload.stage || "New")
  return NextResponse.json({ ok: true, lead })
}
`,
    },
    {
      path: "lib/services/crm.service.ts",
      language: "ts",
      content: `type Lead = {
  id: string
  name: string
  stage: string
}

const leadStore: Lead[] = [
  { id: "lead-1", name: "Acme Corp", stage: "Qualified" },
]

export async function listLeads(): Promise<Lead[]> {
  return leadStore
}

export async function createLead(name: string, stage: string): Promise<Lead> {
  const lead = { id: "lead-" + Date.now(), name, stage }
  leadStore.push(lead)
  return lead
}
`,
    },
  ]
}

function buildReadmeFile({
  name,
  originalPrompt,
  effectivePrompt,
  providerMessage,
}: {
  name: string
  originalPrompt: string
  effectivePrompt: string
  providerMessage?: string | null
}): GeneratedFile {
  return {
    path: "README.md",
    language: "md",
    content: `# ${escapeMultilineText(name)}

Generated with fixed Swift project structure.

## Included Root Tree

- app/
- components/
- hooks/
- lib/
- prisma/
- public/
- styles/
- .env.example
- auth.ts
- components.json
- middleware.ts
- next.config.mjs
- package.json
- postcss.config.mjs
- tsconfig.json

## Original Prompt

> ${escapeMultilineText(originalPrompt)}

## Effective Build Brief

${escapeMultilineText(effectivePrompt)}

## Provider Summary

${escapeMultilineText(providerMessage || "Local scaffold fallback was used.")}
`,
  }
}

export function buildModuleStatusReport({
  projectName,
  prompt,
  intent,
  previewStatus = "success",
  errorMessage,
}: {
  projectName?: string | null
  prompt: string
  intent?: BuildIntent
  previewStatus?: ModuleStatusReport["previewStatus"]
  errorMessage?: string | null
}): ModuleStatusReport {
  const normalized = prompt.toLowerCase()
  const inferredIntent = intent || inferBuildIntent(prompt)
  const ready: ModuleStatusItem[] = [
    {
      name: "Preview shell",
      status: "ready",
      detail: "A browser-safe page is available with mock data and visible build status.",
    },
    {
      name: "App Router structure",
      status: "ready",
      detail: "Core app, components, lib, prisma, public, and route handler folders are represented.",
    },
  ]
  const partial: ModuleStatusItem[] = []
  const planned: ModuleStatusItem[] = []
  const errors: ModuleStatusItem[] = []

  if (inferredIntent === "laundry" || /laundry|dry clean|cuci|setrika/.test(normalized)) {
    ready.push({
      name: "Laundry order flow",
      status: "ready",
      detail: "Order form, service packages, and admin order table are available in the preview.",
    })
    partial.push({
      name: "Pickup and delivery operations",
      status: "partial",
      detail: "Order status uses mock data; courier assignment and notifications can be connected next.",
    })
    planned.push({
      name: "Laundry production tracking",
      status: "planned",
      detail: "Add weighing, payment status, wash progress, and delivery proof with Prisma-backed data.",
    })
  } else if (inferredIntent === "ecommerce" || /belanjaku|marketplace|shopee|seller|buyer|cart|checkout|midtrans/.test(normalized)) {
    ready.push({
      name: "Buyer storefront",
      status: "ready",
      detail: "Product-facing homepage and product API mock are included for preview.",
    })
    partial.push({
      name: "Cart and checkout engine",
      status: "partial",
      detail: "Checkout/order routes use mock payloads; payment provider integration is not connected yet.",
    })
    planned.push(
      {
        name: "Seller Center",
        status: "planned",
        detail: "Add product CRUD, order management, seller analytics, and settlement pages.",
      },
      {
        name: "Admin CMS",
        status: "planned",
        detail: "Add moderation queues, banner CMS, category management, and audit logs.",
      },
      {
        name: "Midtrans webhook",
        status: "planned",
        detail: "Connect signed payment notifications after env keys and database writes are ready.",
      }
    )
  } else if (inferredIntent === "dashboard") {
    ready.push({
      name: "Dashboard overview",
      status: "ready",
      detail: "KPI cards, activity feed, and summary route are available with mock metrics.",
    })
    partial.push({
      name: "Analytics detail",
      status: "partial",
      detail: "Overview data is mocked; drill-down charts and filters are planned.",
    })
  } else if (inferredIntent === "news") {
    ready.push({
      name: "Portal berita publik",
      status: "ready",
      detail: "Hero Desa Buntu, berita terkini, pengumuman warga, dan agenda desa tersedia.",
    })
    ready.push({
      name: "Artikel dan komentar",
      status: "ready",
      detail: "Halaman detail artikel dengan form komentar dan placeholder login Gmail tersedia.",
    })
    partial.push({
      name: "Admin CRUD berita",
      status: "partial",
      detail: "Halaman admin untuk posts dan categories tersedia dengan API route placeholder.",
    })
  } else if (inferredIntent === "booking") {
    ready.push({
      name: "Booking preview",
      status: "ready",
      detail: "Available slots and booking route mock are included.",
    })
    partial.push({
      name: "Real scheduling rules",
      status: "partial",
      detail: "Calendar conflict checks and notifications still need database-backed logic.",
    })
  } else {
    partial.push({
      name: "Domain module",
      status: "partial",
      detail: "The first visible slice is ready; deeper business logic should be implemented in the next prompt.",
    })
  }

  planned.push({
    name: "Production data layer",
    status: "planned",
    detail: "Replace preview mock data with Prisma service calls once schema and env are finalized.",
  })

  if (previewStatus === "error" && errorMessage) {
    errors.push({
      name: "Preview error",
      status: "error",
      detail: errorMessage,
    })
  }

  return {
    projectName: projectName || undefined,
    previewStatus,
    currentPhase: inferCurrentPhase(inferredIntent, normalized),
    ready,
    partial,
    planned,
    errors,
    nextSteps: buildNextSteps(inferredIntent, normalized, previewStatus),
  }
}

function buildModuleStatusDataFile(status: ModuleStatusReport): GeneratedFile {
  return {
    path: "lib/build-status.ts",
    language: "ts",
    content: `export type ModuleStatusState = "ready" | "partial" | "planned" | "error"

export type ModuleStatusItem = {
  name: string
  status: ModuleStatusState
  detail: string
}

export type ModuleStatusReport = {
  projectName?: string
  previewStatus: "success" | "fallback" | "error"
  currentPhase: string
  ready: ModuleStatusItem[]
  partial: ModuleStatusItem[]
  planned: ModuleStatusItem[]
  errors: ModuleStatusItem[]
  nextSteps: string[]
}

export const moduleStatus: ModuleStatusReport = ${JSON.stringify(status, null, 2)}
`,
  }
}

function inferCurrentPhase(intent: BuildIntent, normalizedPrompt: string) {
  if (intent === "laundry" || /laundry|dry clean|cuci|setrika/.test(normalizedPrompt)) return "laundry-order-admin"
  if (/seller|penjual/.test(normalizedPrompt)) return "seller-center"
  if (/admin|cms|moderation|moderasi/.test(normalizedPrompt)) return "admin-cms"
  if (/checkout|payment|midtrans|bayar|pembayaran/.test(normalizedPrompt)) return "checkout-payment"
  if (intent === "ecommerce") return "buyer-storefront"
  if (intent === "dashboard") return "dashboard-overview"
  if (intent === "news") return "village-news-portal"
  if (intent === "booking") return "booking-flow"
  return "preview-first-foundation"
}

function buildNextSteps(intent: BuildIntent, normalizedPrompt: string, previewStatus: ModuleStatusReport["previewStatus"]) {
  if (previewStatus === "error") {
    return [
      "Fix the preview error shown in the status panel.",
      "Regenerate only the broken file after the preview renders.",
      "Continue with the next module once the shell is stable.",
    ]
  }

  if (intent === "laundry" || /laundry|dry clean|cuci|setrika/.test(normalizedPrompt)) {
    return [
      "Connect order form submissions to a persisted Prisma LaundryOrder model.",
      "Add pickup assignment and delivery status transitions.",
      "Add invoice/payment status and customer notification hooks.",
    ]
  }

  if (intent === "ecommerce" || /belanjaku|marketplace|shopee/.test(normalizedPrompt)) {
    return [
      "Implement product CRUD for Seller Center.",
      "Connect cart state to checkout and order routes.",
      "Add Midtrans sandbox webhook with signature validation.",
      "Build Admin moderation for products, sellers, banners, and reports.",
    ]
  }

  if (intent === "news" || /berita|news|artikel|portal|desa|warga|bumdes|pengumuman/.test(normalizedPrompt)) {
    return [
      "Connect posts, categories, and comments to Prisma database writes.",
      "Enable Google/Gmail login with NextAuth before comment publishing.",
      "Protect /admin routes with an admin role and add moderation states for comments.",
    ]
  }

  return [
    "Turn the preview mock data into Prisma-backed services.",
    "Add the next user-facing flow as a small, testable module.",
    "Keep the build status panel updated after each generation.",
  ]
}

function mergeFilesByPath(base: GeneratedFile[], overrides: GeneratedFile[]) {
  const map = new Map<string, GeneratedFile>()

  for (const file of [...base, ...overrides]) {
    const normalizedPath = normalizePath(file.path)
    map.set(normalizedPath, {
      ...file,
      path: normalizedPath,
    })
  }

  return Array.from(map.values()).sort((a, b) => a.path.localeCompare(b.path))
}

function normalizePath(path: string) {
  return path.replace(/\\/g, "/").replace(/^\.\//, "")
}

function inferBuildIntent(prompt: string): BuildIntent {
  const normalized = prompt.toLowerCase()

  if (/(berita|news|artikel|article|portal berita|portal desa|desa|warga|bumdes|pengumuman|agenda desa|kegiatan desa)/i.test(normalized)) {
    return "news"
  }

  if (/(laundry|dry clean|cuci|setrika|laundromat)/i.test(normalized)) {
    return "laundry"
  }

  if (/(marketplace|e-?commerce|shop|store|product|cart|checkout|shopee)/i.test(normalized)) {
    return "ecommerce"
  }

  if (/(booking|reservation|appointment|schedule|reservasi|janji temu|jadwal)/i.test(normalized)) {
    return "booking"
  }

  if (/(crm|lead|pipeline|sales ops|internal tool|pelanggan)/i.test(normalized)) {
    return "crm"
  }

  if (/(dashboard|admin|analytics|report|metric|kpi|sidebar)/i.test(normalized)) {
    return "dashboard"
  }

  if (/(landing page|landing|hero|marketing|cta|conversion)/i.test(normalized)) {
    return "landing"
  }

  if (/(portfolio|personal brand|resume|case study)/i.test(normalized)) {
    return "portfolio"
  }

  return "generic"
}

function inferName(prompt: string) {
  const quoted = prompt.match(/["“](.+?)["”]/)
  if (quoted?.[1]) return quoted[1]

  const named = prompt.match(/(?:named|bernama|name)\s+([a-z0-9][a-z0-9\\s-]{2,30})/i)
  if (named?.[1]) return named[1].trim()

  return null
}

function sanitizeName(input: string) {
  const normalized = input.replace(/\s+/g, " ").trim()
  return normalized.slice(0, 40)
}

function escapeInlineText(value: string) {
  return value
    .replace(/\s+/g, " ")
    .trim()
    .replace(/`/g, "'")
    .replace(/\$/g, "\\$")
}

function escapeMultilineText(value: string) {
  return value.replace(/`/g, "'").replace(/\$/g, "\\$")
}

function serializeForCode(value: string) {
  return JSON.stringify(value).replace(/\$/g, "\\$")
}
